AWSTemplateFormatVersion: 2010-09-09

Description: Lambda@Edge function to add security headers to responses from CloudFront

Metadata:
  Author: Mondo Robot

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Lambda Parameters
        Parameters:
          - Runtime
          - Timeout
          - MemorySize
          - FunctionDescription
      - Label:
          default: Logging
        Parameters:
          - LogsRetentionInDays

Parameters:
  FunctionDescription:
    Default: Adds security headers to response
    Description: The description of the lambda function
    Type: String
  LogsRetentionInDays:
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Default: 7
    Description: 'Specifies the number of days you want to retain log events'
    Type: Number
  MemorySize:
    AllowedValues: [128, 256, 512, 1024]
    Default: 128
    Description: The memory size to use
    Type: Number
  Runtime:
    AllowedValues:
      - nodejs
      - nodejs4.3
      - nodejs6.10
      - nodejs8.10
    Default: nodejs8.10
    Description: The lambda runtime to use for execution
    Type: String
  Timeout:
    Default: 5
    Description: Lambda function execution time in seconds before terminating
    Type: Number

Conditions:
  HasFunctionDescription: !Not [ !Equals [ '', !Ref FunctionDescription ] ]

Resources:
  LambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        # If you change the ZipFile, rename the logical id LambdaVersionV1 to trigger a new version creation!
        ZipFile: !Sub |
          'use strict';

          exports.handler = (event, context, callback) => {
            const response = event.Records[0].cf.response;
            const headers = response.headers;

            // add security headers
            headers['strict-transport-security'] = [
              {
                key: 'Strict-Transport-Security',
                value: 'max-age=31536000; includeSubdomains; preload'
              }
            ];
            headers['x-content-type-options'] = [
              {
                key: 'X-Content-Type-Options',
                value: 'nosniff'
              }
            ];
            headers['x-frame-options'] = [
              {
                key: 'X-Frame-Options',
                value: 'SAMEORIGIN'
              }
            ];
            headers['x-xss-protection'] = [
              {
                key: 'X-XSS-Protection',
                value: '1; mode=block'
              }
            ];
            headers['referrer-policy'] = [
              {
                key: 'Referrer-Policy',
                value: 'no-referrer-when-downgrade'
              }
            ];

            callback(null, response);
          };
      Description: !If [ HasFunctionDescription, !Ref FunctionDescription, !Ref 'AWS::NoValue' ]
      Handler: 'index.handler'
      MemorySize: !Ref MemorySize
      Role: !GetAtt 'LambdaRole.Arn'
      Runtime: !Ref Runtime
      Timeout: !Ref Timeout
  LambdaLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '/aws/lambda/${LambdaFunction}'
      RetentionInDays: !Ref LogsRetentionInDays
  LambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - 'lambda.amazonaws.com'
                - 'edgelambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  LambdaVersionV1:
    Type: 'AWS::Lambda::Version'
    Properties:
      FunctionName: !Ref LambdaFunction

Outputs:
  StackName:
    Value: !Ref 'AWS::StackName'
  FunctionArn:
    Export:
      Name: !Sub ${AWS::StackName}-FunctionArn
    Value: !GetAtt LambdaFunction.Arn
  RoleArn:
    Export:
      Name: !Sub ${AWS::StackName}-RoleArn
    Value: !GetAtt LambdaRole.Arn
  Version:
    Export:
      Name: !Sub ${AWS::StackName}-Version
    Value: !GetAtt LambdaVersionV1.Version
  VersionArn:
    Export:
      Name: !Sub ${AWS::StackName}-VersionArn
    Value: !Ref LambdaVersionV1
