AWSTemplateFormatVersion: 2010-09-09

Description: Master template for generating the Coachlla static site resources

Metadata:
  Author: Mondo Robot

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Github
        Parameters:
          - GithubOwnerAccount
          - GithubOAuthToken
          - GithubRepo
          - GithubBranch
      - Label:
          default: S3 Parameters
        Parameters:
          - SiteBucketName
          - IndexDocument
          - ErrorDocument
          - RedirectHostName
          - RedirectProtocol
          - RedirectStatusCode
      - Label:
          default: CloudFront Parameters
        Parameters:
          - DomainName
          - CloudFrontAliases
          - CertificateArn
          - PriceClass
          - SecurityHeadersEnable
      - Label:
          default: CodePipeline/CodeBuild
        Parameters:
          - PipelineBucket
          - PipelineName
          - BuildType
          - BuildComputeType
          - BuildImage
          - ApiBaseUrl
          - ApiPostsUrl
          - ApiMenuUrl
          - ApiNavMenuUrl
          - ApiMediaUrl
          - ApiArtistsUrl
          - ApiArtistMediaUrl
          - GTMIds
          - GAIds
      - Label:
          default: Basic Auth Parameters
        Parameters:
          - BasicAuthEnable
          - BasicAuthUsername
          - BasicAuthPassword
          - BasicAuthLogsRetentionInDays
      - Label:
          default: Slack Build Notification Parameters
        Parameters:
          - SlackWebhook
          - SlackNotifierLogsRetentionInDays
    ParameterLabels:
      ApiArtistsUrl:
        default: Artists API URL
      ApiArtistMediaUrl:
        default: Artists API Media URL
      ApiBaseUrl:
        default: Base API URL
      ApiMenuUrl:
        default: Menu API URL
      ApiNavMenuUrl:
        default: Nav Menu API URL
      ApiPostsUrl:
        default: Posts API URL
      BasicAuthEnable:
        default: Basic Auth Enable
      BasicAuthLogsRetentionInDays:
        default: Basic Auth Log Retention in Days
      BasicAuthUsername:
        default: Basic Auth Username
      BasicAuthPassword:
        default: Basic Auth Password
      BuildComputeType:
        default: Build Compute Instance Type
      BuildImage:
        default: Build Image
      BuildType:
        default: Build Machine Type
      CertificateArn:
        default: SSL Certificate ARN
      CloudFrontAliases:
        default: Comma separated list of alias domains, can use wildcards
      DomainName:
        default: Site Domain Name
      ErrorDocument:
        default: Error Document Path (e.g. 404.html)
      GAIds:
        default: '[Optional] Comma separated list of Google Analytics IDs'
      GithubBranch:
        default: GitHub Branch
      GithubOAuthToken:
        default: GitHub OAuth Token
      GithubOwnerAccount:
        default: GitHub Owner Account (Can be found in github url /<owner>/<repo>)
      GithubRepo:
        default: GitHub Repository (Can be found in github url /<owner>/<repo>)
      GTMIds:
        default: '[Optional] Comma separated list of Google Tag Manager IDs'
      IndexDocument:
        default: Index Document (e.g. index.html)
      PipelineBucket:
        default: CodePipeline S3 Bucket Name
      PipelineName:
        default: CodePipeline Name
      PriceClass:
        default: CloudFront Price Class
      RedirectHostName:
        default: Redirect Hostname
      RedirectProtocol:
        default: Redirect Protocol (specify to force specific protocol)
      RedirectStatusCode:
        default: Redirect Status Code
      SecurityHeadersEnable:
        default: Enable security headers in responses from CloudFront to user
      SiteBucketName:
        default: Site S3 Bucket Name
      SlackNotifierLogsRetentionInDays:
        default: Slack Lambda Notifier Log Retention In Days
      SlackWebhook:
        default: Slack Webhook URL

Parameters:
  ApiArtistsUrl:
    Default: 'https://s3.amazonaws.com/goeventweb-static.greencopper.com/a01405de1df74e27bf13f23a26670c9b/coachella-2019/data/eng/artists.json'
    Description: Arists data url
    Type: String
  ApiArtistMediaUrl:
    Default: 'https://goevent-images.s3.amazonaws.com/coachella-2019/f3241018/web'
    Description: Arists data url
    Type: String
  ApiBaseUrl:
    Description: Base api url
    Type: String
  ApiMenuUrl:
    Description: Menu api url
    Type: String
  ApiNavMenuUrl:
    Description: Main nav api url
    Type: String
  ApiMediaUrl:
    Description: Media url
    Type: String
  ApiPostsUrl:
    Description: Posts api url
    Type: String
  BasicAuthEnable:
    AllowedValues: [true, false]
    Default: false
    Description: Whether or not to use basic auth
    Type: String
  BasicAuthLogsRetentionInDays:
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Default: 14
    Description: 'Specifies the number of days you want to retain log events'
    Type: Number
  BasicAuthUsername:
    Default: admin
    Description: The basic auth username
    Type: String
  BasicAuthPassword:
    Description: The basic auth password
    NoEcho: true
    Type: String
  BuildComputeType:
    AllowedValues:
      - BUILD_GENERAL1_SMALL
      - BUILD_GENERAL1_MEDIUM
      - BUILD_GENERAL1_LARGE
    Default: BUILD_GENERAL1_SMALL
    Description: Build machine compute type
    Type: String
  BuildImage:
    Default: 'aws/codebuild/nodejs:10.1.0'
    Description: Build machine image
    Type: String
  BuildType:
    AllowedValues:
      - LINUX_CONTAINER
      - WINDOWS_CONTAINER
    Default: LINUX_CONTAINER
    Description: Build machine type
    Type: String
  CertificateArn:
    Description: The ACM certificate to use
    Type: String
  CloudFrontAliases:
    Default: ''
    Description: Comma separated list of aliases, can use wildcard
    Type: CommaDelimitedList
  DomainName:
    Description: The domain for the website
    Type: String
  ErrorDocument:
    Default: 404.html
    Description: The error document to load when pages not found
    Type: String
  GAIds:
    Default: ''
    Description: Comma separated list of Google Analytics IDs
    Type: String
  GithubBranch:
    Description: Github branch
    Default: develop
    Type: String
  GithubOAuthToken:
    Description: Personal access token attached to the github account for repo access
    NoEcho: true
    Type: String
  GithubOwnerAccount:
    Description: Github owner account. Can be found in github url /<owner>/<repo>
    Default: mondorobot
    Type: String
  GithubRepo:
    Default: coa.website
    Description: Githut repo name. Can be found in github url /<owner>/<repo>
    Type: String
  GTMIds:
    Default: ''
    Description: Comma separated list of Google Tag Manager IDs
    Type: String
  IndexDocument:
    Default: index.html
    Description: The root document of the directory
    Type: String
  PipelineBucket:
    Default: ''
    Description: The bucket name to store pipeline artifacts
    Type: String
  PipelineName:
    Default: coachella-static-pipeline
    Description: The name of the code pipeline
    Type: String
  PriceClass:
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All
    Default: PriceClass_All
    Description: The price class that corresponds to which edge servers are used.
    Type: String
  RedirectHostName:
    Default: ''
    Description: The hostname to redirect to
    Type: String
  RedirectProtocol:
    Default: https
    Description: The protocol to use when redirecting (http, https)
    Type: String
  RedirectStatusCode:
    AllowedValues: [301, 302, 303, 307]
    Default: 302
    Description: The status code to use on redirect
    Type: String
  SecurityHeadersEnable:
    AllowedValues: [true, false]
    Default: true
    Description: Enables security headers in the response from CloudFront to users
    Type: String
  SiteBucketName:
    Default: coachella-static
    Description: The name to use when generating the S3 bucket for the static site
    Type: String
  SlackNotifierLogsRetentionInDays:
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Default: 1
    Description: Specifies the number of days to retain log events
    Type: Number
  SlackWebhook:
    Description: '[Optional] webhook url for slack build notifications'
    Type: String

Conditions:
  HasBasicAuth: !Equals [ !Ref BasicAuthEnable, true ]
  HasSlackWebhook: !Not [ !Equals [ '', !Ref SlackWebhook ] ]
  HasLeadingSlashErrorDocument: !Equals [ '', !Select [ 0, !Split [ '/', !Ref ErrorDocument ] ] ]
  HasSecurityHeaders: !Equals [ !Ref SecurityHeadersEnable, true ]

Resources:
  CloudFrontModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        Aliases: !Join [ ',', !Ref CloudFrontAliases ]
        BasicAuthLambdaVersionArn: !If [ HasBasicAuth, !GetAtt LambdaBasicAuthModule.Outputs.VersionArn, !Ref 'AWS::NoValue' ]
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref DomainName
        ErrorDocumentPath: !If [ HasLeadingSlashErrorDocument, !Ref ErrorDocument, !Sub '/${ErrorDocument}' ]
        PriceClass: !Ref PriceClass
        S3WebsiteOriginDomain: !Select [ 2, !Split [ '/', !GetAtt S3SiteBucketModule.Outputs.WebsiteURL ] ]
        SecurityHeadersLambdaVersionArn: !If [ HasSecurityHeaders, !GetAtt LambdaSecurityHeadersModule.Outputs.VersionArn, !Ref 'AWS::NoValue' ]
      TemplateURL: https://s3.amazonaws.com/cf-coachella/static-site/cloudfront.yaml
  CodePipelineModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ApiArtistsUrl: !Ref ApiArtistsUrl
        ApiArtistMediaUrl: !Ref ApiArtistMediaUrl
        ApiBaseUrl: !Ref ApiBaseUrl
        ApiMediaUrl: !Ref ApiMediaUrl
        ApiMenuUrl: !Ref ApiMenuUrl
        ApiNavMenuUrl: !Ref ApiNavMenuUrl
        ApiPostsUrl: !Ref ApiPostsUrl
        BuildType: !Ref BuildType
        BuildComputeType: !Ref BuildComputeType
        BuildImage: !Ref BuildImage
        GAIds: !Ref GAIds
        GithubOwnerAccount: !Ref GithubOwnerAccount
        GithubOAuthToken: !Ref GithubOAuthToken
        GithubRepo: !Ref GithubRepo
        GithubBranch: !Ref GithubBranch
        GTMIds: !Ref GTMIds
        PipelineBucket: !Ref PipelineBucket
        PipelineName: !Ref PipelineName
        WebsiteBucketArn: !GetAtt S3SiteBucketModule.Outputs.Arn
        WebsiteBucketName: !GetAtt S3SiteBucketModule.Outputs.BucketName
      TemplateURL: https://s3.amazonaws.com/cf-coachella/static-site/codepipeline.yaml
  LambdaBasicAuthModule:
    Condition: HasBasicAuth
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Username: !Ref BasicAuthUsername
        Password: !Ref BasicAuthPassword
        LogsRetentionInDays: !Ref BasicAuthLogsRetentionInDays
      TemplateURL: https://s3.amazonaws.com/cf-coachella/static-site/lambda-basic-auth.yaml
  LambdaBuildNotifierModule:
    Condition: HasSlackWebhook
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        CodePipelines: !GetAtt CodePipelineModule.Outputs.PipelineName
        LogsRetentionInDays: !Ref SlackNotifierLogsRetentionInDays
        SlackWebhook: !Ref SlackWebhook
      TemplateURL: https://s3.amazonaws.com/cf-coachella/static-site/lambda-pipeline-slack-notifier.yaml
  LambdaSecurityHeadersModule:
    Condition: HasSecurityHeaders
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/cf-coachella/static-site/lambda-security-headers.yaml
  S3SiteBucketModule:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        BucketName: !Ref SiteBucketName
        IndexDocument: !Ref IndexDocument
        ErrorDocument: !If [ HasLeadingSlashErrorDocument, !Select [ 1, !Split [ '/', !Ref ErrorDocument ] ], !Ref ErrorDocument ]
        RedirectHostName: !Ref RedirectHostName
        RedirectProtocol: !Ref RedirectProtocol
        RedirectStatusCode: !Ref RedirectStatusCode
      TemplateURL: https://s3.amazonaws.com/cf-coachella/static-site/s3-website.yaml

Outputs:
  DnsEndpoint:
    Value: !GetAtt CloudFrontModule.Outputs.DnsEndpoint
  PipelineBucket:
    Description: The bucket holding the code pipeline artifacts
    Value: !GetAtt CodePipelineModule.Outputs.PipelineBucket
  WebsiteUrl:
    Description: Static website url
    Value: !GetAtt CloudFrontModule.Outputs.DnsHostname
  WebsiteBucket:
    Description: The bucket holding the static website
    Value: !GetAtt S3SiteBucketModule.Outputs.BucketName
  WordpressWebhookUrl:
    Description: Webhook URL for pushing change notifications from wordpress
    Value: !GetAtt CodePipelineModule.Outputs.WordpressWebhookUrl
