---
AWSTemplateFormatVersion: "2010-09-09"

Description: >
  VPC Endpoint for S3 bucket

Metadata:
  Authors:
    Description: Mondo Robot

  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: VPC Endpoint Parameters
        Parameters:
          - VpcId
          - RouteTableIds
    ParameterLabels:
      RouteTableIds:
        default: Route Table Ids
      VpcId:
        default: VPC Id

Parameters:
  RouteTableIds:
    Description: Comma separated list of route table ids
    Type: CommaDelimitedList
  VpcId:
    Description: The VPC to connect the endpoint to
    Type: AWS::EC2::VPC::Id

Resources:
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds: !Ref RouteTableIds
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId: !Ref VpcId
Outputs:
  StackName:
    Description: Stack name
    Value: !Sub '${AWS::StackName}'
  Endpoint:
    Description: The VPC endpoint to S3
    Value: !Ref S3Endpoint
    Export:
      Name: !Sub '${AWS::StackName}-S3Endpoint'
